### PR TITLE
added possible values for age filter

### PR DESCRIPTION
**Pull request by flyinggab**

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @gabrielecipriano.

**Comment by jncd** [comment]
@gabrielecipriano Thanks for this PR. I just want to check that this filter applies to the live v0.3 version too. 
(We cherry-picked it so the new text appears both on the `master` branch and https://docs.pivotal.io/service-instance-manager/0-3/using.html#filter-instances )

**Comment by flyinggab** [comment]
Hi @jncd , sorry for the late reply.

No it does not apply to 0.3

**Comment by RichardJJG** [comment]
@gabrielecipriano, thanks, I've changed the v0.3 docs accordingly. FYI, @jncd.

**Pull request merged**
